manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: zmklocale
      url-base: https://github.com/joelspadin/zmk-locales.git
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: locale
      remote: zmklocale
      revision: main
  self:
    path: config
